name: Manual Monitoring Test

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - health
          - status

jobs:
  test-monitoring:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests psutil
    
    - name: Validate APP_URL
      run: |
        if [ -z "${{ secrets.APP_URL }}" ]; then
          echo "Error: APP_URL secret is not set"
          exit 1
        fi
    
    - name: Run health check
      if: github.event.inputs.test_type == 'health' || github.event.inputs.test_type == 'all'
      env:
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        echo "Running health check..."
        python scripts/health_check.py $APP_URL
    
    - name: Run status check
      if: github.event.inputs.test_type == 'status' || github.event.inputs.test_type == 'all'
      env:
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        echo "Running status check..."
        python scripts/status_check.py $APP_URL
    
    - name: Summary
      run: |
        echo "## Monitoring Test Results" >> $GITHUB_STEP_SUMMARY
        echo "✅ Tests completed" >> $GITHUB_STEP_SUMMARY
        echo "Check the logs above for detailed results" >> $GITHUB_STEP_SUMMARY
